### ISSUE TITLE
Temperature reading wrong when temperature is negative

### ISSUE THREAD

**Issue by leramleram** [syssi/esphome-modbus-solax-x1#38]
The temperature reading of the inverter seems to be a signed value, but the component interprets it as unsigned.
This results in an overflow when Temperature is below 0°C.

![grafik](https://user-images.githubusercontent.com/4068474/218020133-7e8b205c-b61e-4c67-a76c-9860c3962a84.png)

**Comment by syssi** [comment]
Good catch! I will prepare a fix!

**Comment by syssi** [comment]
I pushed a fix to `main`. Please recompile & flash your device and give it another try while it's still cold. ;-)

**Comment by leramleram** [comment]
Too late... Temperature´s above 0°C ;-)
Have to give it a try tomorrow!

![grafik](https://user-images.githubusercontent.com/4068474/218036194-cf5c0fb0-021c-44c6-858c-33bb24ec175b.png)

**Comment by leramleram** [comment]
That´s a Bingo!
![grafik](https://user-images.githubusercontent.com/4068474/218245817-8f5a6e1c-4710-4c81-aeb7-6ec3c49ea86d.png)

Temperature is now correct when < 0°C

Thank you!

**Comment by syssi** [comment]
Perfect! Thanks for keeping your eyes open! :-)
